<?php

namespace App\Http\Resources;

class AnswersResource extends Resource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return $this->filterFields([
            'id' => $this->id,
            'question_id' => $this->question_id,
            'title' => $this->title,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ]);
    }

    public function hide(array $fields)
    {

        return parent::hide($fields); // TODO: Change the autogenerated stub
    }

    public static function collection($resource)
    {
        $s = tap(new AnswersResourceCollection($resource), function($collection) {
            $collection->collects = __CLASS__;
        });

        return $s;
    }
}
